---
title: "Untitled"
author: "Ranae Dietzel"
date: "August 3, 2016"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Reproducibilty

## Why
* If you have to do something once, you are going to have to do it 1000 times  
  + analysis is iterative  
  + requests/collaborators are unpredictable  
  + data grows
* If you can't reproduce what you did, it's impossible to find the mistakes
* If you can't reproduce what you did, it is not credible
  

## Why
* If you can reproduce what you did, others can too  
* They can either use the information to perform similar analyses, or build upon all the work you did

## How, data collection
* Reproducibility begins before you head to the field or lab
* Establish a recorded protocol complete with references  
  +Test if everyone can follow the protocol before they are left on their own
  +Bring the protocol with you to the field and record deviations
Do not assume you will remember anything. Remembering indicates there is a piece of data that exists only in your head!  
* Take notes on anything that might be slightly relevant, but don't go overboard -- you should have established most of the required information before you got to the field  
* Take pictures in the field/lab. . .you gotta

## 
