---
title: "Untitled"
author: "Ranae Dietzel"
date: "September 24, 2016"
output: html_document
---

What is R? An environment.  
How did it start?  
How many people use R?
  This is what it looks like.  
R can do many basic things (stats).
R has its own data (cars).  

R has a lot of packages (7,801).
What is a package?
  Vignettes (different styles), data  
  How to read  
  
Let me tell you about some packages.
  nlme (more stats) 
  agricolae  (stats for agron)  
  soilR (modeling)  
  meteo(spatial modeling) 
  metagenomeSeq  
  apsimR (run another program from R)  
  
There are also great visualization packages.  
Obviously there is knitr and RMarkdown -- also bookR 

You will use multiple packages together

Who makes these packages? 

How do you keep up with packages?
Follow the R community
  Twitter
  R-weekly.org  
  https://www.r-bloggers.com/  
  http://citizen-statistician.org/  
  Google  
  Stackoverflow  
  UseR  
  
Become part of the R community, if you want  

How R will help us become good data stewards  




  
  