---
title: "Hello, R"
author: "Ranae Dietzel & Andee Kaplan"
ratio: 16x10
output:
  rmdshower::shower_presentation:
    self_contained: false
    katex: true
    theme: ribbon
---

##Outline  
####What is R?  
  R is an environment -- language, software  
R is an integrated suite of software facilities for data manipulation, calculation and graphical display. It includes

an effective data handling and storage facility,
a suite of operators for calculations on arrays, in particular matrices,
a large, coherent, integrated collection of intermediate tools for data analysis,
graphical facilities for data analysis and display either on-screen or on hardcopy, and
a well-developed, simple and effective programming language which includes conditionals, loops, user-defined recursive functions and input and output facilities.
The term "environment" is intended to characterize it as a fully planned and coherent system, rather than an incremental accretion of very specific and inflexible tools, as is frequently the case with other data analysis software.  

#Base R  

####Open source, free  
####Community built  
  Many ways to do many things
  Packages  
    Old school vs. new package descriptions  
  
  
You seem to be falling prey to a common misconception that "R" is some monolithic tool, when in fact it is a herd of cats.
   -- Jeff Newmiller (in response to a user who did not look for packages)
      R-help (December 2013)  

####

Spencer Graves: 'The sun never sets on the (former) British Empire.' Today, it never sets on R-Help.  



Why use R?  
  Community (help, support)  
  
  
  



How, what, why, where, when 

  

