---
title: "590RD R Notebook"
output:
  html_notebook: default
  html_document: default
---


####Similar courses
[mine-cetinkaya-rundel](https://github.com/mine-cetinkaya-rundel/2016-06-27-first-ds-course-user)  
[cbahlai](https://github.com/cbahlai/OSRR_course)  
Colin Rundel at Duke  
Jenny Bryan

####Interesting tools  
[Atlassian](https://www.atlassian.com/software/sourcetree)  
[Wercker](http://wercker.com/)


####Great blogs/tutorials  
Find style guides -- R, SQL
[Writing code](http://ropensci.github.io/reproducibility-guide/sections/writingCode/)
[Code and Data for the Social Sciences, A Practitioner's Guide](http://web.stanford.edu/~gentzkow/research/CodeAndData.xhtml)
[How to share data with a statistician](https://github.com/jtleek/datasharing)
[Checklist](http://ropensci.github.io/reproducibility-guide/sections/checklist/)
[5 Reasons Why to Learn Reproducibility](http://chance.amstat.org/2014/09/reproducible-paradigm/)
[Raw data organization](http://kbroman.org/dataorg/)
[Steps to reproducible research](http://kbroman.org/steps2rr/)
[Markdown for scientists](https://github.com/karthik/markdown_science)



####Small skills our students don't have
* Code organization and best practice (chunks, annotations)
* Writing reproducible questions
* Awareness of the online community
* Keeping track of the language they are learning

####Thoughts
* **Make more detailed course outline**
* Week one assignment
* Another recruitment email -- top ten list 
* Venn diagram
* **Need to collect and discuss datasets**
* Group project description development

####Outline
1. Git, GitHub, and R Markdown \dotfill Week 1
1. Standards of reproducible data collection \dotfill Week 2
1. Relational Databases and SQL \dotfill Week 3-4
1. Data architecture \dotfill Week 5
1. Introduction to \texttt{R} \dotfill Week 6-7
1. Data munging and wrangling \dotfill Week 8-9
1. Visualization \dotfill Week 10
1. Reproducibility and Dynamic Documents \dotfill Week 11-12
1. External Data Sources \dotfill Week 13
1. Special Data Types \dotfill Week 14
1. Project presentations \dotfill Week 15

####Other
Can "reproducible question" be a time-flexible homework?










